services:
  app:
    container_name: wirehook
    image: runabol/wirehook
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # sudo certbot certonly -v --standalone -d wirehook.net -d www.wirehook.net
      - /etc/letsencrypt/archive/wirehook.net:/etc/ssl
    ports:
      - "443:443"
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge